spring:
  profiles:
    active: dev
  threadPool:
    corePoolSize: 30
    maxPoolSize: 100
    queueCapacity: 100
    keepAliveSeconds: 300
datasource:
  write: &common-conf
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  read1: *common-conf
  read2: *common-conf
transaction:
  list:
    - matchName: save*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: del*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: add*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: edit*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: upd*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: rem*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: create*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: insert*
      rule: PROPAGATION_REQUIRED,-Exception
    - matchName: query*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: is*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: find*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: get*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: load*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: count*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: list*
      rule: PROPAGATION_SUPPORTS,-Exception
    - matchName: check*
      rule: PROPAGATION_SUPPORTS,-Exception
mybatis:
  type-aliases-package: com.demo.model
  mapper-locations: classpath:mapper/*.xml


