server:
  port: 8080
#多数据源 1主2从
datasource:
 #从库数量
  readSize: 2
   # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  #主库
  write:
    url: jdbc:mysql://121.43.109.70:3308/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz2wsx
  read1:
    url: jdbc:mysql://121.43.109.70:3308/test?useUnicode=true&characterEncoding=utf-8
    username: javanose_read
    password: 123qwe
  read2:
    url: jdbc:mysql://121.43.109.70:3308/test?useUnicode=true&characterEncoding=utf-8
    username: javanose_read
    password: 123qwe
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    timeout: 0
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  port:
    dubbo: 20881
